// Auto-generated by TensAi Blueprint-to-C++ translator

#include "ABP_SecurityTurret.h"
#include "GameFramework/Actor.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SpotLightComponent.h"
#include "Components/SphereComponent.h"
#include "Components/PointLightComponent.h"
#include "Components/AudioComponent.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "GameFramework/Pawn.h"
#include "Engine/World.h"

ABP_SecurityTurret::ABP_SecurityTurret()
{
	TurretBase = CreateDefaultSubobject<USceneComponent>(TEXT("TurretBase"));
	RootComponent = TurretBase;

	BaseMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("BaseMesh"));
	BaseMesh->SetupAttachment(TurretBase);

	PivotPoint = CreateDefaultSubobject<USceneComponent>(TEXT("PivotPoint"));
	PivotPoint->SetupAttachment(BaseMesh);

	ArmMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ArmMesh"));
	ArmMesh->SetupAttachment(PivotPoint);

	CameraHead = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("CameraHead"));
	CameraHead->SetupAttachment(ArmMesh);

	CameraSpotLight = CreateDefaultSubobject<USpotLightComponent>(TEXT("CameraSpotLight"));
	CameraSpotLight->SetupAttachment(CameraHead);

	DetectionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("DetectionSphere"));
	DetectionSphere->SetupAttachment(CameraHead);

	StatusLight = CreateDefaultSubobject<UPointLightComponent>(TEXT("StatusLight"));
	StatusLight->SetupAttachment(PivotPoint);

	ServoAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("ServoAudio"));
	ServoAudio->SetupAttachment(PivotPoint);

	AlarmAudio = CreateDefaultSubobject<UAudioComponent>(TEXT("AlarmAudio"));
	AlarmAudio->SetupAttachment(TurretBase);

	PrimaryActorTick.bCanEverTick = true;
}

void ABP_SecurityTurret::BeginPlay()
{
	Super::BeginPlay();

	// [call_printstring_1]
	UKismetSystemLibrary::PrintString(this, TEXT("Security Turret Online"), true, true, FLinearColor(0.0000f, 0.6600f, 1.0000f, 1.0000f), 2.000000f, FName(TEXT("None")));
}

void ABP_SecurityTurret::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	const double Pure_0 = (CurrentYaw + (RotationSpeed * UGameplayStatics::GetWorldDeltaSeconds(this)));
	FHitResult Out_SweepHitResult_1;
	// [branch_4]
	if (bIsActive)
	{
		// [set_currentyaw_10]
		CurrentYaw = Pure_0;
		// [call_k2_setrelativerotation_12]
		PivotPoint->K2_SetRelativeRotation(UKismetMathLibrary::MakeRotator(0.0f, 0.0f, Pure_0), false, Out_SweepHitResult_1, false);
	}
}

void ABP_SecurityTurret::NotifyActorBeginOverlap(AActor* OtherActor)
{
	Super::NotifyActorBeginOverlap(OtherActor);

	const FVector Pure_3 = CameraHead->K2_GetComponentLocation();
	// [cast_pawn_15]
	APawn* CastResult_2 = Cast<APawn>(OtherActor);
	if (CastResult_2)
	{
		// Sequence 0
		// [set_btargetdetected_17]
		bTargetDetected = true;
		// [node_18]
		OnTargetDetected.Broadcast(OtherActor);
		// Sequence 1
		// [call_printstring_19]
		UKismetSystemLibrary::PrintString(this, TEXT("INTRUDER DETECTED - FIRING!"), true, true, FLinearColor(1.0000f, 0.0000f, 0.0000f, 1.0000f), 2.000000f, FName(TEXT("None")));
		// Sequence 2
		// [node_25]
		UClass* Spawned_4Class = StaticLoadClass(AActor::StaticClass(), nullptr, TEXT("/Game/Blueprints/BP_Projectile.BP_Projectile_C"));
		AActor* Spawned_4 = Spawned_4Class ? GetWorld()->SpawnActor<AActor>(Spawned_4Class, UKismetMathLibrary::MakeTransform(Pure_3, UKismetMathLibrary::FindLookAtRotation(Pure_3, OtherActor->K2_GetActorLocation()), FVector(1.000000,1.000000,1.000000))) : nullptr;
	}
}

void ABP_SecurityTurret::NotifyActorEndOverlap(AActor* OtherActor)
{
	Super::NotifyActorEndOverlap(OtherActor);

	// [set_btargetdetected_27]
	bTargetDetected = false;
	// [node_28]
	OnTargetLost.Broadcast();
}
